name: Release to NPM

on: [pull_request]

jobs:
  check-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          clean: true

      - name: Install Dependencies
        run: yarn --no-lockfile

      - name: Build package
        run: yarn build
