name: Release to NPM

on:
  push:
    tags:
    - '*'

jobs:
  build-and-deploy:
    if: github.repository == 'lucide-icons/lucide'

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/\v}

      - uses: actions/checkout@v2
        with:
          clean: true

      - name: Install Dependencies
        run: yarn --no-lockfile

      - name: Build package
        run: yarn build

      - name: Set package.json version
        run: yarn version --new-version ${{ steps.get_version.outputs.VERSION }} --no-git-tag-version

      - name: Set Auth Token
        run: yarn config set 'npmRegistries["//registry.npmjs.org"].npmAuthToken' ${{ secrets.NPM_TOKEN }}

      - name: publish
        run: yarn publish

      - name: Commit package.json
        run: |
          git add package.json
          git -c user.name="Lucide Bot" -c user.email="lucide-bot@users.noreply.github.com" \
            commit -m ":package: Bump version to ${{ steps.get_version.outputs.VERSION }}" --no-verify --quiet
          git remote set-url --push origin https://lucide-bot:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git push origin HEAD:master

